/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * mi-deck api
 * mi-deck api description
 * OpenAPI spec version: 1.0
 */
import type { CreateTimelineDtoType } from './createTimelineDtoType';

export interface CreateTimelineDto {
  /** The ID of the server session this timeline belongs to */
  serverSessionId: string;
  /** User-defined name for the timeline */
  name: string;
  /** Type of the timeline */
  type: CreateTimelineDtoType;
  /** Required if type is LIST. The ID of the Misskey list. */
  listId?: string;
  /** Required if type is CHANNEL. The ID of the Misskey channel. */
  channelId?: string;
}
