/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * mi-deck api
 * mi-deck api description
 * OpenAPI spec version: 1.0
 */
import type { CreateServerSessionResponseEntityServerType } from './createServerSessionResponseEntityServerType';

export interface CreateServerSessionResponseEntity {
  id: string;
  userId: string;
  origin: string;
  serverToken: string;
  serverType: CreateServerSessionResponseEntityServerType;
  createdAt: string;
  updatedAt: string;
}
