/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * mi-deck api
 * mi-deck api description
 * OpenAPI spec version: 1.0
 */

export type CreateServerSessionResponseEntityServerType = typeof CreateServerSessionResponseEntityServerType[keyof typeof CreateServerSessionResponseEntityServerType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateServerSessionResponseEntityServerType = {
  Misskey: 'Misskey',
  OtherServer: 'OtherServer',
} as const;
