/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * mi-deck api
 * mi-deck api description
 * OpenAPI spec version: 1.0
 */

/**
 * Type of the server
 */
export type ServerSessionInfoServerType = typeof ServerSessionInfoServerType[keyof typeof ServerSessionInfoServerType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServerSessionInfoServerType = {
  Misskey: 'Misskey',
  OtherServer: 'OtherServer',
} as const;
