/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * mi-deck api
 * mi-deck api description
 * OpenAPI spec version: 1.0
 */
import type { ServerSessionInfoServerType } from './serverSessionInfoServerType';

export interface ServerSessionInfo {
  /** ID of the server session */
  id: string;
  /** Origin URL of the server */
  origin: string;
  /** Type of the server */
  serverType: ServerSessionInfoServerType;
  /** Token for the server session */
  serverToken: string;
}
