/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * mi-deck api
 * mi-deck api description
 * OpenAPI spec version: 1.0
 */

export interface ServerInfoEntity {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  serverSessionId: string;
  iconUrl: string;
  faviconUrl: string;
  themeColor: string;
}
