/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * mi-deck api
 * mi-deck api description
 * OpenAPI spec version: 1.0
 */

export interface SignUpDto {
  email: string;
  password: string;
  username: string;
}
