/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * mi-deck api
 * mi-deck api description
 * OpenAPI spec version: 1.0
 */

export type TimelineWithServerSessionEntityType = typeof TimelineWithServerSessionEntityType[keyof typeof TimelineWithServerSessionEntityType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TimelineWithServerSessionEntityType = {
  HOME: 'HOME',
  LOCAL: 'LOCAL',
  GLOBAL: 'GLOBAL',
  LIST: 'LIST',
  USER: 'USER',
  CHANNEL: 'CHANNEL',
} as const;
