/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * mi-deck api
 * mi-deck api description
 * OpenAPI spec version: 1.0
 */
import type { TimelineWithServerSessionEntityType } from './timelineWithServerSessionEntityType';
import type { TimelineWithServerSessionEntityListId } from './timelineWithServerSessionEntityListId';
import type { TimelineWithServerSessionEntityChannelId } from './timelineWithServerSessionEntityChannelId';
import type { ServerSessionInfo } from './serverSessionInfo';

export interface TimelineWithServerSessionEntity {
  id: string;
  serverSessionId: string;
  name: string;
  type: TimelineWithServerSessionEntityType;
  listId?: TimelineWithServerSessionEntityListId;
  channelId?: TimelineWithServerSessionEntityChannelId;
  createdAt: string;
  updatedAt: string;
  /** Associated server session details */
  serverSession: ServerSessionInfo;
}
