/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * mi-deck api
 * mi-deck api description
 * OpenAPI spec version: 1.0
 */
import type { TimelineEntityType } from './timelineEntityType';
import type { TimelineEntityListId } from './timelineEntityListId';
import type { TimelineEntityChannelId } from './timelineEntityChannelId';

export interface TimelineEntity {
  id: string;
  serverSessionId: string;
  name: string;
  type: TimelineEntityType;
  listId?: TimelineEntityListId;
  channelId?: TimelineEntityChannelId;
  createdAt: string;
  updatedAt: string;
}
