packages:
  - apps/**

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bcrypt
  - esbuild
  - lefthook
  - msw
  - prisma
  - unrs-resolver
