/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * mi-deck api
 * mi-deck api description
 * OpenAPI spec version: 1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateServerSessionDto,
  CreateServerSessionResponseEntity,
  ServerInfoEntity,
  UpdateServerInfoDto
} from '../../models';

import { customInstance } from '../../mutator/custom-instance';




export const serversessionsControllerCreate = (
    createServerSessionDto: CreateServerSessionDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CreateServerSessionResponseEntity>(
      {url: `/api/v1/server-sessions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createServerSessionDto, signal
    },
      );
    }
  


export const getServersessionsControllerCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof serversessionsControllerCreate>>, TError,{data: CreateServerSessionDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof serversessionsControllerCreate>>, TError,{data: CreateServerSessionDto}, TContext> => {

const mutationKey = ['serversessionsControllerCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof serversessionsControllerCreate>>, {data: CreateServerSessionDto}> = (props) => {
          const {data} = props ?? {};

          return  serversessionsControllerCreate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ServersessionsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof serversessionsControllerCreate>>>
    export type ServersessionsControllerCreateMutationBody = CreateServerSessionDto
    export type ServersessionsControllerCreateMutationError = void

    export const useServersessionsControllerCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof serversessionsControllerCreate>>, TError,{data: CreateServerSessionDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof serversessionsControllerCreate>>,
        TError,
        {data: CreateServerSessionDto},
        TContext
      > => {

      const mutationOptions = getServersessionsControllerCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const serversessionsControllerGetList = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<CreateServerSessionResponseEntity[]>(
      {url: `/api/v1/server-sessions`, method: 'GET', signal
    },
      );
    }
  

export const getServersessionsControllerGetListQueryKey = () => {
    return [`/api/v1/server-sessions`] as const;
    }

    
export const getServersessionsControllerGetListInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof serversessionsControllerGetList>>>, TError = void>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof serversessionsControllerGetList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getServersessionsControllerGetListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof serversessionsControllerGetList>>> = ({ signal }) => serversessionsControllerGetList(signal);

      

      

   return  { queryKey, queryFn,   staleTime: 10000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof serversessionsControllerGetList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ServersessionsControllerGetListInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof serversessionsControllerGetList>>>
export type ServersessionsControllerGetListInfiniteQueryError = void


export function useServersessionsControllerGetListInfinite<TData = InfiniteData<Awaited<ReturnType<typeof serversessionsControllerGetList>>>, TError = void>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof serversessionsControllerGetList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof serversessionsControllerGetList>>,
          TError,
          Awaited<ReturnType<typeof serversessionsControllerGetList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServersessionsControllerGetListInfinite<TData = InfiniteData<Awaited<ReturnType<typeof serversessionsControllerGetList>>>, TError = void>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof serversessionsControllerGetList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof serversessionsControllerGetList>>,
          TError,
          Awaited<ReturnType<typeof serversessionsControllerGetList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServersessionsControllerGetListInfinite<TData = InfiniteData<Awaited<ReturnType<typeof serversessionsControllerGetList>>>, TError = void>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof serversessionsControllerGetList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useServersessionsControllerGetListInfinite<TData = InfiniteData<Awaited<ReturnType<typeof serversessionsControllerGetList>>>, TError = void>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof serversessionsControllerGetList>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getServersessionsControllerGetListInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions , queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getServersessionsControllerGetListQueryOptions = <TData = Awaited<ReturnType<typeof serversessionsControllerGetList>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serversessionsControllerGetList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getServersessionsControllerGetListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof serversessionsControllerGetList>>> = ({ signal }) => serversessionsControllerGetList(signal);

      

      

   return  { queryKey, queryFn,   staleTime: 10000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof serversessionsControllerGetList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ServersessionsControllerGetListQueryResult = NonNullable<Awaited<ReturnType<typeof serversessionsControllerGetList>>>
export type ServersessionsControllerGetListQueryError = void


export function useServersessionsControllerGetList<TData = Awaited<ReturnType<typeof serversessionsControllerGetList>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof serversessionsControllerGetList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof serversessionsControllerGetList>>,
          TError,
          Awaited<ReturnType<typeof serversessionsControllerGetList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServersessionsControllerGetList<TData = Awaited<ReturnType<typeof serversessionsControllerGetList>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serversessionsControllerGetList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof serversessionsControllerGetList>>,
          TError,
          Awaited<ReturnType<typeof serversessionsControllerGetList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServersessionsControllerGetList<TData = Awaited<ReturnType<typeof serversessionsControllerGetList>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serversessionsControllerGetList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useServersessionsControllerGetList<TData = Awaited<ReturnType<typeof serversessionsControllerGetList>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serversessionsControllerGetList>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getServersessionsControllerGetListQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const serversessionsControllerUpdateServerInfo = (
    updateServerInfoDto: UpdateServerInfoDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ServerInfoEntity>(
      {url: `/api/v1/server-sessions/update-server-info`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateServerInfoDto, signal
    },
      );
    }
  


export const getServersessionsControllerUpdateServerInfoMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof serversessionsControllerUpdateServerInfo>>, TError,{data: UpdateServerInfoDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof serversessionsControllerUpdateServerInfo>>, TError,{data: UpdateServerInfoDto}, TContext> => {

const mutationKey = ['serversessionsControllerUpdateServerInfo'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof serversessionsControllerUpdateServerInfo>>, {data: UpdateServerInfoDto}> = (props) => {
          const {data} = props ?? {};

          return  serversessionsControllerUpdateServerInfo(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ServersessionsControllerUpdateServerInfoMutationResult = NonNullable<Awaited<ReturnType<typeof serversessionsControllerUpdateServerInfo>>>
    export type ServersessionsControllerUpdateServerInfoMutationBody = UpdateServerInfoDto
    export type ServersessionsControllerUpdateServerInfoMutationError = void

    export const useServersessionsControllerUpdateServerInfo = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof serversessionsControllerUpdateServerInfo>>, TError,{data: UpdateServerInfoDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof serversessionsControllerUpdateServerInfo>>,
        TError,
        {data: UpdateServerInfoDto},
        TContext
      > => {

      const mutationOptions = getServersessionsControllerUpdateServerInfoMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    