root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "tmp/main"
  full_bin = "APP_ENV=dev GIN_MODE=debug ./tmp/main"
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go"]
  kill_delay = "1s"
  delay = 1000
  stop_on_error = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
