name: CI
on:
  pull_request:

jobs:
  storybook-test:
    strategy:
      matrix:
        node-version: [22]
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.9.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright
        run: pnpm run front exec playwright  install  --wtih-deps
      - name: Build Storybook
        run: pnpm run front build-storybook --quiet

      - name: Run Storybook tests
        run: pnpm run front test-storybook:ci

  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.9.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install & Build
        run: pnpm i

      # 環境変数を設定 (シークレットから取得)

      # ビルドを実行
      - name: pnpm run server db:generate
        run: pnpm run server db:generate
      - name: pnpm run build
        run: pnpm build

